# ─────────────────────────────────────────────────────
# PRODUCTION — image depuis le registry
# ─────────────────────────────────────────────────────

services:

  # ── 1. PostgreSQL ─────────────────────────────────
  postgres:
    image: postgres:15-alpine
    container_name: prod-postgres

    environment:
      POSTGRES_DB      : ${POSTGRES_DB}
      POSTGRES_USER    : ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_prod:/var/lib/postgresql/data

    # ✅ Pas de depends_on ici — géré par le workflow
    restart: always

  # ── 2. Redis ──────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: prod-redis

    volumes:
      - redis_prod:/data

    restart: always

  # ── 3. Flask API ──────────────────────────────────
  app:
    image: ghcr.io/${GITHUB_USERNAME}/stack-complete:latest
    container_name: prod-api

    environment:
      APP_ENV     : production
      APP_VERSION : ${APP_VERSION}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL   : redis://redis:6379/0

    # ✅ depends_on simple — sans condition service_healthy
    depends_on:
      - postgres
      - redis

    restart: always

  # ── 4. Nginx ──────────────────────────────────────
  nginx:
    image: nginx:alpine
    container_name: prod-nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - app

    restart: always

# ── Volumes persistants ───────────────────────────
volumes:
  postgres_prod:
  redis_prod: