upstream flask_api {
    server app:5000;
}

server {
    listen 80;

    # ── Routes de l'API ───────────────────────────
    location / {
        proxy_pass         http://flask_api;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;

        # Timeouts
        proxy_connect_timeout 30s;
        proxy_read_timeout    30s;
    }

    # ── Health check (pas de log) ─────────────────
    location /health {
        proxy_pass http://flask_api;
        access_log off;
    }

    # ── Readiness check ───────────────────────────
    location /ready {
        proxy_pass http://flask_api;
        access_log off;
    }
}